import { Inter } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import Navbar from "../components/Layout/Navbar";
import SnackBarProvider from "../components/Provider/SnackbarProvider";
import ThemeWrapper from "../components/Theme/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const styles = {
  padding: "75px 50px",
  margin: "0 auto",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SnackBarProvider>
          <ThemeWrapper>
            <Navbar />
            <Container maxWidth="xl" sx={styles}>
              {children}
            </Container>
          </ThemeWrapper>
        </SnackBarProvider>
      </body>
    </html>
  );
}
